name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3, 8.4, 8.5]
        laravel: [8.*, 9.*, 10.*, 11.*, 12.*, 13.*]

        exclude:
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*
          - php: 8.1
            laravel: 13.*
          - php: 8.2
            laravel: 13.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, readline
          coverage: none

      - name: Install dependencies
        run: |
          if [ "${{ matrix.laravel }}" = "8.*" ]; then TESTBENCH="^6.0"; fi
          if [ "${{ matrix.laravel }}" = "9.*" ]; then TESTBENCH="^7.0"; fi
          if [ "${{ matrix.laravel }}" = "10.*" ]; then TESTBENCH="^8.0"; fi
          if [ "${{ matrix.laravel }}" = "11.*" ]; then TESTBENCH="^9.0"; fi
          if [ "${{ matrix.laravel }}" = "12.*" ]; then TESTBENCH="^10.0"; fi
          if [ "${{ matrix.laravel }}" = "13.*" ]; then TESTBENCH="^11.0"; fi
          
          composer config audit.abandoned ignore
          composer config security.advisories.block false
          
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${TESTBENCH}" --dev --no-interaction --no-update
          
          composer update --prefer-dist --no-interaction --no-audit

      - name: Execute tests
        run: vendor/bin/phpunit